### ISSUE TITLE
time per keyframe

### ISSUE THREAD

**Issue by KyanoBoi** [1Toothless/BetterDiscord-Animated-Status#3]
i can't change it, if i try a diffrint number it just goes back to 2400.
i can't go lower at least, higher works fine

**Comment by 1Benito11** [comment]
When I tried deleting this limit, my discord was lagging.

**Comment by 1Toothless** [comment]
Hey Thank you for opening the issues. I will look into fixing that issues. Thank you for letting me know.

Kind Regards
1Toothless

**Comment by 1Toothless** [comment]
The limit for time per keyframe has now been changed to min 600ms. And it won't be changed to lower as it will higher the chance of you getting banned or your discord will lag a lot.

Kind Regards
1Toothless
