### ISSUE TITLE
The download link doesnt work anymore

### ISSUE THREAD

**Issue by C00PERLY** [1Toothless/BetterDiscord-Animated-Status#4]
When clicking on the download link, It sends me to error 404 instead of the download.
![Desktop Screenshot 2021 04 02 - 10 33 09 53](https://user-images.githubusercontent.com/81375537/113398449-e6ba0a80-939e-11eb-9fc9-7158bf4fa2d1.png)

**Comment by 1Toothless** [comment]
Hey Thank you for opening the issues the download link should be working now again.

Kind Regards
1Toothless
